### ISSUE TITLE
Set Size Limit?

### ISSUE THREAD

**Issue by searchy2** [Sunzxyong/Tiny#28]
Is it possible to set a MAX size limit for the returned image? If not, what is the best way to make sure that the image is maximum quality under a certain size? Thank you for the great library!

**Comment by umeitime** [comment]
压缩后的图片质量很不好啊，自己还要判断图片大小才能确定是否压缩。

**Comment by Sunzxyong** [comment]
@umeitime 不需要自己判断的，内部自动以当前手机分辨率为最佳显示效果进行压缩的

**Comment by Sunzxyong** [comment]
@umeitime The maximum size of the image is  screen resolution. Or you can set the size of the compressed images.

**Comment by umeitime** [comment]
我的意思是比如图片本身小于200kb的话，我就不压缩了，因为图本身小，再压缩就非常模糊了。

**Comment by searchy2** [comment]
What I mean by size is the file size. I would like all images to be compressed below 500KB/0.5MBs. Can the library do that or do I need to test the sizes myself and then recompress if the file is still larger?

**Comment by Sunzxyong** [comment]
@umeitime 图片小于200kb？如果是质量压缩，文件本身的大小为200kb，通常用为图片上传，你可以判断文件大小是否大于进行压缩，如果大于可以设置压缩后期望大小（options.size）来进行压缩大小设置。如果是图片本身所占内存压缩为不大于200kb，内部衡量是对图片与当前设备分辨率大小进行判断的，小于设备分辨率则自动不进行压缩

**Comment by Sunzxyong** [comment]
@searchy2 Yes. The library will compress files for you in the expected sizes automatically. For you example, you can set ‘FileCompressOptions.size = 500’ .

**Comment by searchy2** [comment]
Thank you so much! An option to set file size is just what I was looking for :+1:
