### ISSUE TITLE
isKeepSampling Explanation

### ISSUE THREAD

**Issue by searchy2** [Sunzxyong/Tiny#29]
Wow, the images compressed by this library are amazing in quality! Almost indistinguishable from the originals but 1/50th the size! 

My question is about the isKeepSampling option. What exactly does this option do? I assume that it means whether or not to keep the original image width and height. But when I set it to true, a 5520x4140 image was compressed to 960x1280. I thought the option would keep the dimensions at 5520x4140. So, what exactly does this option do? I notice no changes in the output file when setting it to true or false.

**Comment by Sunzxyong** [comment]
Yes, it will keep the original width and height of image.

**Comment by searchy2** [comment]
The option does not seem to work. Even when I set it to true, the compressed image still decreases in size. Could this option be affected by setting a sample size limit? I set the output file size limit to 500KB.

**Comment by Sunzxyong** [comment]
@searchy2 Thanks, i have fixed this problem, see version **v0.0.7.**

**Comment by searchy2** [comment]
Incredible! Thanks for fixing this bug. This library is absolutely amazing and unbelievably, sometimes the compressed image is actually BETTER than the original!
