### ISSUE TITLE
关于压缩过程中占用大亮内存而无法释放的问题

### ISSUE THREAD

**Issue by yuanxiaofan** [Sunzxyong/Tiny#3]
在阅读完《也谈图片压缩》这篇文章后受益匪浅，感谢作者的分享！之前也看过一篇有关于Android使用JNI的方式压缩图片的文章，都会存在一个问题就是瞬间占用大量内存而无法主动释放，多的一下能增加50M之多，在应用已经使用比较高的情况下很容易造成OOM，不知道作者有没有什么方案？

**Comment by Sunzxyong** [comment]
@yuanxiaofan 你好~，在正常的使用场景中没有出现这个问题。请问下是否在跑Demo过程中出现大概内存增加？原因是Demo中对大图也直接解码，目的为了比较原图与压缩图的效果。在正常使用中不会出现那么大内存。关于你说的遇到jni中内存增加无法释放，可能是lockpixel没有及时对bitmap的进行unlockpixel亦或是没有释放某些对象等。同时本项目遵循良好代码规范以及设计。

**Comment by yuanxiaofan** [comment]
好的，我自己写一个demo试一试！谢谢你的解答！

**Comment by Sunzxyong** [comment]
再补充一点，Tiny中为了保证良好的图片显示质量，采取和Wechat一样的策略，控制在主流的720x1280中以及当前设备的屏幕分辨率中，在压缩过程中会有一个temp bitmap，这个bitmap在下次GC时将会回收。同时你也可以考虑用RGB_565，能表示的颜色也达65536种。

**Comment by yuanxiaofan** [comment]
谢谢作者的分享！在内存方面确实能够及时释放！
