### ISSUE TITLE
在红米Note 跑有问题 UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Chenhengquan** [Sunzxyong/Tiny#30]
我在自己的项目中发现  红米note 有问题   Android 4.4

07-31 20:42:34.723 28333-28871/com.xxx..imagepicker W/ContextImpl: Failed to ensure directory: /storage/sdcard1/Android/data/com.xx.imagepicker/files: 400

07-31 20:42:34.723 28333-28871/com.xxx.imagepicker W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/xxx/plugin/imagepicker/libjpegturbo/JpegTurboCompressor;

在Nexus 5x 中正常

**Comment by Sunzxyong** [comment]
@Chenhengquan 日志不完整，为什么JpegTurboCompressor包名会是这个com/xxx/plugin/imagepicker/libjpegturbo/JpegTurboCompressor？

**Comment by Chenhengquan** [comment]
我是直接把代码拷贝过来自己项目后发现就出现这些错误了，主要是压缩成file 的时候出错了

**Comment by Sunzxyong** [comment]
@Chenhengquan 用依赖会出错吗？
