### ISSUE TITLE
DEFAULT_MAX_COMPRESS_SIZE  这个属性可以不要 final 修饰吗

### ISSUE THREAD

**Issue by Chenhengquan** [Sunzxyong/Tiny#31]
在批量压缩  需要配置最大边长  希望可以修改为调用者动态修改  感谢

**Comment by Sunzxyong** [comment]
@Chenhengquan 下一个版本将会提供这个接口

**Comment by Chenhengquan** [comment]
@Sunzxyong  thanks！ 这个库在低端手机避免OOM的效果太棒了

**Comment by Chenhengquan** [comment]
我再把项目上传到自己的maven 会出现这个问题
W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/zxy/libjpegturbo/JpegTurboCompressor;
