### ISSUE TITLE
如果失败了拿不到失败原因

### ISSUE THREAD

**Issue by szhupeng** [Sunzxyong/Tiny#34]
如果压缩过程中出现异常，比如存储空间不够导致无法压缩，你直接屏蔽了异常，根本拿不到，app无法进行友好提示

**Comment by Sunzxyong** [comment]
@szhupeng 你可以在返回false时候进行一些重试提示，对于异常内存不足、线程、图片压缩等异常暂时没有具体进行外抛，后一版本可放出来

**Comment by szhupeng** [comment]
这个应该是要放出来的，不然用户根本不知道异常的原因，无法排查

**Comment by Sunzxyong** [comment]
已经更新，版本v0.1.0 , 详情看 https://github.com/Sunzxyong/Tiny/issues/38
