### ISSUE TITLE
压缩返回的图片名称，可以自定义吗？

### ISSUE THREAD

**Issue by Vector-SMG** [Sunzxyong/Tiny#45]

**Comment by Sunzxyong** [comment]
@PantomZ 可以的，配置FileCompressOptions#outfile属性，自定义压缩图片的file

**Comment by sushanqiang** [comment]
试了好像也没效果

**Comment by byteluo** [comment]
加1

**Comment by byteluo** [comment]
它必须要格式正确才行，这个有尴尬

**Comment by yuaihen** [comment]
必须要指定文件后缀才行`.jpg`，光指定输出文件夹不行。

**Comment by Sunzxyong** [comment]
@sushanqiang @byteluo 指定压缩目录用 compressDirectory 属性
