### ISSUE TITLE
outfile属性

### ISSUE THREAD

**Issue by BinarySatan** [Sunzxyong/Tiny#55]
outfile属性 内部压缩的时候都重新赋值了!! 怎么设置...

**Comment by Sunzxyong** [comment]
@BinarySatan 不好意思，才看到。
内部会重新赋值，是在外部传入的outfile文件不可用的情况下，必须保证outfile是一个以.jpg结尾的文件地址

**Comment by BinarySatan** [comment]
恩，我下载了库 自己改代码了。~
