### ISSUE TITLE
best compression config

### ISSUE THREAD

**Issue by ahmed56734** [Sunzxyong/Tiny#67]
first of all I want to appreciate the good work done on this library

I don't have knowledge about compressions algorithms 
but I want to figure the most suitable Bitmap.Config I should use in my app.
-my app lets user take screenshots images
-images are saved in sqlite database as byte array
-then uploaded later to the server
what is the best config for my case ?

**Comment by ahmed56734** [comment]
they are normal screenshots look like this
![screenshot_1540904108](https://user-images.githubusercontent.com/10393214/47719429-d7758680-dc53-11e8-87dd-81d00726495c.png)
![screenshot_1540904182](https://user-images.githubusercontent.com/10393214/47719536-2b806b00-dc54-11e8-98a4-8da5eec7d312.png)

**Comment by Sunzxyong** [comment]
@ahmed56734 
In your case, you should compress the size of the screenshots image file, which you can do in the following way.

```
        Tiny.FileCompressOptions options = new Tiny.FileCompressOptions();
        Tiny.getInstance().source("").asFile().withOptions(options).compress(new FileCallback() {
            @Override
            public void callback(boolean isSuccess, String outfile, Throwable t) {
                //return the compressed file path
            }
        });
        
        //or sync compress.
        FileResult result = Tiny.getInstance().source("").asFile().withOptions(options).compressSync();
```
the 'options' can use the default configuration, you just need to pass in the file path(source),
