### ISSUE TITLE
请问老师如何设置宽与高的baseline啊？

### ISSUE THREAD

**Issue by kevinGan** [Sunzxyong/Tiny#68]
我在
options里设置width跟height都是2480之后，最终压缩出来的图变成了正方形，而不是保留原有的长宽比例了
看了一下源码，觉得貌似是应该两个值都设置的时候，是计算一次原图宽高才确定baseline的，然后根据baseline去等比例压缩原图像素的
求老师指导
用的1.0版本
代码是这样写的
`
maxLength = 2048;
ptions.width = maxLength;
options.height = maxLength;
options.compressDirectory = FilePathSetting.COMPRESS_PATH;
FileResult result = Tiny.getInstance().source(bigFilePath).asFile().withOptions(options).compressSync();
`

**Comment by Sunzxyong** [comment]
@kevinGan 因为你宽和高都设置了2048，这个就是正方形了，你设置宽或高一个就行，默认等比例压缩的

**Comment by kevinGan** [comment]
> @kevinGan 因为你宽和高都设置了2048，这个就是正方形了，你设置宽或高一个就行，默认等比例压缩的

我试过只设一个了，这样会导致变成默认的1280了，看了代码逻辑，若不是width跟height都大于0的时候，会判断为不是用自定义数值，而是用默认值

![image](https://user-images.githubusercontent.com/4114257/52103725-0a982f00-2622-11e9-8361-55bd773f46f5.png)

**Comment by Sunzxyong** [comment]
@kevinGan 刚刚看了下代码，确实如此，这两天我加一个设置baseline接口，感谢反馈~

**Comment by kevinGan** [comment]
感谢老师

**Comment by Sunzxyong** [comment]
@kevinGan 使用v1.1.0版本，在BitmapCompressOptions#baseline参数中设置。
