### ISSUE TITLE
拍照压缩时图片裁剪了

### ISSUE THREAD

**Issue by HoneyWorld** [Sunzxyong/Tiny#72]
Tiny.FileCompressOptions options=new Tiny.FileCompressOptions();
        options.outfile= src;
        options.overrideSource=true;
        //已当前手机的宽高作为图片的宽高20190428
        options.width= ScreenUtils.getScreenWidth();
        options.height=ScreenUtils.getScreenHeight();
        options.size=100;
设置压缩的 宽高时，出现图片被自动裁剪的情况，按照默认的就没有裁剪，有没有大佬知道原因

**Comment by Sunzxyong** [comment]
@HoneyWorld 你用手机的宽高设为图片的，当图片宽高比与手机不一样时，当然会出现裁剪呀。这种你不需要主动设置宽高，tiny内部默认会采取屏幕最佳的比例进行压缩

**Comment by HoneyWorld** [comment]
@Sunzxyong 我测试当我设置options.baseline=1920时候，图片并没有进行裁剪，就是与默认的1280相比，压缩的时间变长了，其他还不错，感谢回答！

**Comment by Sunzxyong** [comment]
@HoneyWorld 对的，默认的baseline基线是1280的，如果想要更大的图片，设置更高的基线即可以满足，这种方式可以保持原始图片的宽高比

**Comment by HoneyWorld** [comment]
恩恩，多谢解惑！
