### ISSUE TITLE
android Q适配

### ISSUE THREAD

**Issue by HoneyWorld** [Sunzxyong/Tiny#78]
希望楼主能对android Q进行适配

**Comment by Sunzxyong** [comment]
好的，会最近尽快处理

HoneyWorld <notifications@github.com>于2019年9月17日 周二下午4:57写道：

**Comment by Sunzxyong** [comment]
或者可以提交一个pr，保持好代码规范

HoneyWorld <notifications@github.com>于2019年9月17日 周二下午4:57写道：

**Comment by HoneyWorld** [comment]
@Sunzxyong 感谢楼主，楼主辛苦！
